Library/Models/Book.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Library.Models
{
    public class Book
    {
        public int Id { get; set; }

        public string Title { get; set; }

        public string Authtor { get; set; }

        public int Year { get; set; }

        public string Language { get; set; }

        public string Genre { get; set; }

        public ICollection<Comment> Comments { get; set; }

        public Evaluation Evaluation { get; set; }

        public Reservation Reservation { get; set; }

        public Status Status { get; set; }

        public string Publisher { get; set; }

        public string Description { get; set; }

        public string Image { get; set; }

        public List<Tracking> TrackingList { get; set; }

        public Book(string name)
        {
            Description = "Нет описания";
            Comments = new List<Comment>();
            TrackingList = new List<Tracking>();
            Image = "/images/NoImage.jpg";
        }
        public Book()
        {
            Description = "Нет описания";
            Comments = new List<Comment>();
            Evaluation = new Evaluation()
            {
                Id = Id,
                Average = 0,
                BookId = Id,
                Users = new List<string>()

            };
            TrackingList = new List<Tracking>();
            Image = "/images/NoImage.jpg";
        }
    }
}

Library/Controllers/BookController.cs
using Library.Models;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Library.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Library.Services.BookContorlServices;
using Microsoft.AspNetCore.Hosting;
using BusinessLayer.InrefacesRepository;
using Microsoft.AspNetCore.Identity;
using System.Linq;

namespace Library.Controllers
{
    public class BookController : Controller
    {
        private readonly IBooksRepository bookControl;

        private readonly IWebHostEnvironment env;

        private readonly ITrackingsRepository trackings;

        private readonly UserManager<User> userManager;

        public BookController(IBooksRepository bookControl, IWebHostEnvironment env, ITrackingsRepository trackings, UserManager<User> userManager)
        {
            this.bookControl = bookControl;
            this.env = env;
            this.trackings = trackings;
            this.userManager = userManager;
        }

        //Get-контроллер.Возрат страницы для добавления книг
        //ДОСТУПНА ТОЛЬКО ДЛЯ РОЛИ "librarian"
        [Authorize(Roles = RolesConfig.LIBRARIAN)]
        [HttpGet]
        public IActionResult AddBook()
        {
            return View();
        }

        //Post-контроллер.Обработка формы для добавления книг
        [HttpPost]
        public async Task<IActionResult> AddBook(AddBookViewModel model)
        {
            await bookControl.AddBook(model, env.WebRootPath);
            //Возврат в начальную страницу
            return RedirectToAction("Index", "Home");

        }

        //Контоллер для удаление книг по id
        //ДОСТУПНА ТОЛЬКО ДЛЯ РОЛИ "librarian"
        [Authorize(Roles = RolesConfig.LIBRARIAN)]
        [HttpGet]
        public async Task<IActionResult> DeleteBook(int? id)
        {
            await bookControl.DeleteBook(id);
            return RedirectToAction("ListBook");
        }

        //Контроллер для возрата книг(фильтрация по имени, языку, автору и жанру; пагинация)
        [AllowAnonymous]
        [Authorize]
        public IActionResult ListBook(BookFilterModel model)
        {
            var modelBooks = bookControl.ListBook(model);
            if (User.Identity.IsAuthenticated)
            {
                modelBooks.Trackings = trackings.GetTrackingsByUserId(userManager.GetUserId(User)).ToList();
                ViewBag.userId = userManager.GetUserId(User);
            }

            return View(modelBooks);
        }

        //Get-контроллер. Для получения одной книги по id
        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> GetThisBook(int? id)
        {
            return View(await bookControl.GetThisBook(id));

        }

        //Post-контроллер.Добавление комментария
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> AddComment(CommentViewModel comment, string UserName)
        {
            await bookControl.AddComment(comment, UserName);
            return RedirectToAction("GetThisBook", new { id = comment.BookId });
        }

        //Post-контроллер.Добавление оценки
        public async Task<IActionResult> AddEvaluation(EvaluationViewModel evaluation)
        {
            await bookControl.AddEvaluation(evaluation);
            return RedirectToAction("GetThisBook", new { id = evaluation.BookId });
        }

        [Authorize(Roles = RolesConfig.LIBRARIAN)]
        [HttpGet]
        public IActionResult Edit(int? id)
        {
            return View(bookControl.Edit(id));
        }

        //Post-контроллер. Редактирование информации о книг
        [HttpPost]
        [Authorize(Roles = RolesConfig.LIBRARIAN)]
        public IActionResult Edit(EditBookViewModel edit)
        {
            bookControl.Edit(edit);
            return RedirectToAction("GetThisBook", new { id = edit.Id });
        }

    }
}

Library/Controllers/TrackingController.cs
using System.Linq;
using BusinessLayer.InrefacesRepository;
using Library.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Library.Controllers
{
    //Контроллер для отслеживание бронированных книг
    [Authorize]
    public class TrackingController : Controller
    {
        private readonly UserManager<User> userManager;

        private readonly ITrackingsRepository trackingsRepostiroy;

        public TrackingController(UserManager<User> _userManager, ITrackingsRepository trackingsRepostiroy)
        {
            userManager = _userManager;
            this.trackingsRepostiroy = trackingsRepostiroy;
        }

        //Добавления пользователя в список для отслеживание книг
        [HttpGet]
        public IActionResult Track(int bookId)
        {
            trackingsRepostiroy.Add(bookId, userManager.GetUserId(User));
            return RedirectToAction("ListBook", "Book");
        }

        //Уаление пользователя от списка 
        public IActionResult UnTrace(int bookId)
        {
            trackingsRepostiroy.Delete(bookId, userManager.GetUserId(User));
            return RedirectToAction("ListBook", "Book");
        }

    }
}

Library/Views/Book/AddBook.cshtml
@model Library.ViewModels.AddBookViewModel
@{
    ViewData["Title"] = "AddBook";
}
<style>
    .register {
        background-color: white;
        height: auto;
        margin-top: 2%;
        padding-bottom: 2%;
        border-radius: 30px;
    }
</style>
<div class="row">
    
    <div class="container  col-md-4 col-md-push-4 register  center-block register ">
        <h2>Добавить новую книгу</h2>
        <form method="post" asp-action="AddBook" enctype="multipart/form-data">
            <div>
                <label asp-for="Title"></label><br />
                <input class="form-control" asp-for="Title" />
            </div>
            <div>
                <label asp-for="Year"></label><br />
                <input class="form-control" asp-for="Year" />
                <span asp-validation-for="Year"></span>
            </div>
            <div>
                <label asp-for="Language"></label><br />
                <input class="form-control" asp-for="Language" />
                <span asp-validation-for="Language"></span>
            </div>
            <div>
                <label asp-for="Genre"></label><br />
                <input class="form-control" asp-for="Genre" />
                <span asp-validation-for="Genre"></span>
            </div>
            <div>
                <label asp-for="Authtor"></label><br />
                <input class="form-control" asp-for="Authtor" />
                <span asp-validation-for="Authtor"></span>
            </div>
            <div>
                <label asp-for="Publisher"></label><br />
                <input class="form-control" asp-for="Publisher" />
                <span asp-validation-for="Publisher"></span>
            </div>
            <div>
                <div>
                    <label asp-for="Image">Обложка</label><br />
                    <input name="Image" type="file" class="form-control" />
                </div>
                <input type="submit" class="btn btn-primary" value="Добваить" />
            </div>
    </form>
  </div>
   </div>

Library/Views/Book/Edit.cshtml
@model Library.ViewModels.EditBookViewModel
@{
    ViewBag.Title = "Редактирование книги";
}
<form asp-action="Edit" asp-controller="Book">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <input type="text" asp-for="Title" />
    </div>
    <div class="form-group">
        <img style="border:dashed; color:red" src="@Url.Content(Model.Image)" />
    </div>
    <div class="form-group">
        <label asp-for="Authtor" class="control-label">Автор</label>
        <input type="text" asp-for="Authtor" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Year" class="control-label">Год</label>
        <input type="number" asp-for="Year" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Language" class="control-label">Язык</label>
        <input type="text" asp-for="Language" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Genre" class="control-label">Жанр</label>
        <input type="text" asp-for="Genre" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Publisher" class="control-label">Издатель</label>
        <input type="text" asp-for="Publisher" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Description" class="control-label">Описание</label>
       <textarea asp-for="Description" class="form-control" ></textarea>
    </div>
    <div class="form-group">
        <input type="submit" value="Сохранить" class="btn btn-default" />
    </div>
</form>

Library/Views/Book/GetthisBook.cshtml
@model Library.ViewModels.BookViewModel
@{
    ViewData["Title"] = "GetthisBook";
}
<style>
  .container{
      padding-top:12px;
  }
  table{
      font-size:2em;
  }
  .comment{
      width:80%;
  }
  .panel-title{
      background-color:cyan;
  }
 
</style>
<h1>@Model.Title</h1>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-6">
            <img height="630" width="450" style="border:dashed; color:red"  src="@Url.Content(Model.Image)" />
        </div>
        <div class="col-md-6 ">
            <table class="table  ">
                <tr>
                    <th> Название:</th>
                    <td>@Model.Title</td>
                </tr>
                <tr>
                    <th>Язык:</th>
                    <td>@Model.Language</td>
                </tr>
                <tr>
                    <th>Автор:</th>
                    <td>@Model.Authtor</td>
                </tr>
                <tr>
                    <th>Жанр:</th>
                    <td>@Model.Genre</td>
                </tr>
                <tr>
                    <th>Год:</th>
                    <td>@Model.Year </td>
                </tr>
                <tr>
                    <th>Статус:</th>
                    <td>
                        @switch (Model.Status)
                        {
                            case Status.Available:
                                @:Есть в наличии
                                break;
                            case Status.NotAvailable:
                                @:Нет в наличии
                                break;
                            case Status.Booked:
                                @:Забронирован
                                break;
                        }
                    </td>
                </tr>
                <tr>
                    <th>Описание:</th>
                    <td>
                        @Model.Description
                    </td>
                </tr>

            </table>
        </div>
    </div>
    @if (User.IsInRole("librarian"))
    {
        <div class="container ">
            <form method="get" asp-action="Edit" asp-controller="Book" asp-route-id="@Model.Id">
                <input type="submit" class="btn-danger" value="Изменить" />
            </form>
        </div>
    }
    @if (User.Identity.IsAuthenticated)
    {
        <div class="container ">
            <form method="get" asp-action="CreateReserv" asp-controller="Reservation" asp-route-id="@Model.Id">
                <input type="submit" class="btn btn-primary" value="Забронировать" />
            </form>
        </div>
        <div class="container">
            <p class="h1">Оценка:@Model.Evaluation.Average</p>
        </div>
        @if (!Model.Evaluation.Users.Contains(User.Identity.Name))
        {
            <div class="container">

                <form method="post" asp-action="AddEvaluation" asp-controller="Book" asp-route-BookId="@Model.Id" asp-route-user="@User.Identity.Name">

                    <select name="Score">
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                        <option value="5">5</option>
                    </select>

                    <input type="submit" class="btn-success glyphicon-star" />
                </form>

            </div>
        }
        <div class="container ">
            <div class="row">
                <div class="container">
                    <form class="comment" method="post" asp-action="AddComment" asp-controller="Book" asp-route-BookId="@Model.Id">
                        <label for="CommentString">Написать комментарии:</label><br />
                        <textarea class="col-md-10 form-control center-block " maxlength="120" rows="1" cols="90" draggable="false" name="CommentString"></textarea> <br />
                        <input type="submit" class="btn btn-success" value="Отправить" />
                    </form>
                    <h3>Коментарии <span class="count">@Model.Comments.Count</span></h3>
                    <hr />
                    @if (Model.Comments.Count != 0)
                    {
                        <div class="comment">
                            @foreach (Comment c in Model.Comments)
                            {

                                <div class="panel panel-primary">

                                    <div class="panel-title">
                                        @c.NameUser
                                    </div>
                                    <div class="panel-body">
                                        @c.CommentString
                                    </div>
                                </div>
                            }

                        </div>
                    }
                    else
                    {
                        @:Нет коментарии
                    }
                </div>
            </div>
        </div>

    }
</div>

Library/Views/Book/ListBook.cshtml
@using Library.Models
@using Library.ViewModels

@model Library.ViewModels.AllListBookViewModel
<!--импортируем tag-хелперы проекта-->
@addTagHelper "*, Library"
@{
    ViewData["Title"] = "GetBook";
}
<h1>Список книг</h1>
<form method="get">
    <div class="form-group form-inline">
        <table>
            <tr>
                <td>
                    <label class="control-label">Имя:</label>
                    <input type="text" name="Title" value="@Model.FilterViewModel.SelectedTitle" class="form-control" />
                </td>
                <td>
                    <label class="control-label">Язык</label>
                    <input type="text" name="Language" value="@Model.FilterViewModel.SelectedLanguage" class="form-control" />
                </td>
                <td>
                    <label class="control-label">Автор</label>
                    <input type="text" name="Authtor" value="@Model.FilterViewModel.SelectedAuthor" class="form-control" />
                </td>
                <td>
                    <label>Жанр</label>
                    <input type="text" name="Genre" value="@Model.FilterViewModel.SelectedGenre" class="form-control" />
                </td>
            </tr>
            <tr>
                <td>
                    <label>Издатель</label>
                    <input type="text" name="Publisher" value="@Model.FilterViewModel.SelectedPublisher" class="form-control" />
                </td>
                <td>
                    <input type="submit" value="Фильтр" class="btn btn-default" />
                </td>
<tr>
        </table>
    
    </div>
</form>
<table class="table">
    <tr>
        <th>
            <a asp-action="ListBook"
               asp-route-sortOrder="@(Model.SortViewModel.NameSort)"
              asp-route-title="@(Model.FilterViewModel.SelectedTitle)"
           asp-route-language="@(Model.FilterViewModel.SelectedLanguage)"
           asp-route-sortorder="@(Model.SortViewModel.Current)"
           asp-route-genre="@(Model.FilterViewModel.SelectedGenre)"
            asp-route-author="@(Model.FilterViewModel.SelectedAuthor)">
                Имя
                </a>
        </th>
        <th>
            <a asp-action="ListBook"
               asp-route-sortOrder="@(Model.SortViewModel.AuthorSort)"
               asp-route-title="@(Model.FilterViewModel.SelectedTitle)"
               asp-route-language="@(Model.FilterViewModel.SelectedLanguage)"
               asp-route-sortorder="@(Model.SortViewModel.Current)"
               asp-route-genre="@(Model.FilterViewModel.SelectedGenre)"
               asp-route-author="@(Model.FilterViewModel.SelectedAuthor)">
                Имя автора
                </a>
        </th>
        <th>
            <a asp-action="ListBook"
               asp-route-sortOrder="@(Model.SortViewModel.LangSort)"
               asp-route-title="@(Model.FilterViewModel.SelectedTitle)"
               asp-route-language="@(Model.FilterViewModel.SelectedLanguage)"
               asp-route-sortorder="@(Model.SortViewModel.Current)"
               asp-route-genre="@(Model.FilterViewModel.SelectedGenre)"
               asp-route-author="@(Model.FilterViewModel.SelectedAuthor)">
                Язык
                </a>
        </th>
        <th>
            <a asp-action="ListBook"
               asp-route-sortOrder="@(Model.SortViewModel.PubSort)"
               asp-route-title="@(Model.FilterViewModel.SelectedTitle)"
               asp-route-language="@(Model.FilterViewModel.SelectedLanguage)"
               asp-route-sortorder="@(Model.SortViewModel.Current)"
               asp-route-genre="@(Model.FilterViewModel.SelectedGenre)"
               asp-route-author="@(Model.FilterViewModel.SelectedAuthor)">
                Статус
                </a>
        </th>
       
        @if(User.IsInRole(RolesConfig.LIBRARIAN))
        {
        <th>
            Настройки
        </th>
        }
    </tr>
    @foreach (BookViewModel u in Model.Books)
    {
        <tr>
            <td><a asp-action="GetThisBook" asp-controller="Book" asp-route-id="@u.Id">@u.Title</a></td>
            <td>@u.Authtor</td>
            <td>@u.Language</td>
            <td>
                @switch (u.Status)
                {
                    case Status.Available:
                        @:Есть в наличии
                        break;
                    case Status.NotAvailable:
                        @:Нет в наличии
                        break;
                    case Status.Booked:
                        @:Забронирован
                        break;
                        case Status.Passed:
                        @:Сдан
                         break;
                    }

            </td>
            <td>
                <p>
                    @if (@User.IsInRole(RolesConfig.LIBRARIAN))
                    {
                        <a asp-controller="Book" asp-action="DeleteBook" asp-route-id="@u.Id">Удалить</a>
                    }
                    @if (u.Status == Status.Available && User.Identity.IsAuthenticated)
                    {
                        <a asp-action="CreateReserv" asp-controller="Reservation" asp-route-id="@u.Id">Забронировать</a>
                    }
                    else if ((u.Status == Status.Booked || u.Status == Status.Passed) && User.Identity.IsAuthenticated)
                    {
                        @if (Model.Trackings.FirstOrDefault(t => ViewBag.userId == t.UserId) == null)
                        {
                            
                            <a asp-action="Track" asp-controller="Tracking" asp-route-bookId="@u.Id">Отслеживать</a>
                        }
                        else
                        {
                            <a asp-action="UnTrace" asp-controller="Tracking" asp-route-bookId="@u.Id">Отменить отслеживание</a>
                        }

                    }
                </p>
            </td>
        </tr>
    }
</table>
<page-link page-model="@Model.PageViewModel" page-action="ListBook"
           page-url-title="@(Model.FilterViewModel.SelectedTitle)"
           page-url-language="@(Model.FilterViewModel.SelectedLanguage)"
           page-url-sortorder="@(Model.SortViewModel.Current)"
           page-url-genre="@(Model.FilterViewModel.SelectedGenre)"
            page-url-author="@(Model.FilterViewModel.SelectedAuthor)"
            page-url-page="@Model.PageViewModel.PageNumber"
           ></page-link>