Library/Controllers/BookController.cs
using Library.Models;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Library.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Library.Services.BookContorlServices;
using Microsoft.AspNetCore.Hosting;
using BusinessLayer.InrefacesRepository;
using Microsoft.AspNetCore.Identity;
using System.Linq;

namespace Library.Controllers
{
    public class BookController : Controller
    {
        private readonly IBooksRepository bookControl;

        private readonly IWebHostEnvironment env;

        private readonly ITrackingsRepository trackings;

        private readonly UserManager<User> userManager;

        public BookController(IBooksRepository bookControl, IWebHostEnvironment env, ITrackingsRepository trackings, UserManager<User> userManager)
        {
            this.bookControl = bookControl;
            this.env = env;
            this.trackings = trackings;
            this.userManager = userManager;
        }

        //Get-контроллер.Возрат страницы для добавления книг
        //ДОСТУПНА ТОЛЬКО ДЛЯ РОЛИ "librarian"
        [Authorize(Roles = RolesConfig.LIBRARIAN)]
        [HttpGet]
        public IActionResult AddBook()
        {
            return View();
        }

        //Post-контроллер.Обработка формы для добавления книг
        [HttpPost]
        public async Task<IActionResult> AddBook(AddBookViewModel model)
        {
            await bookControl.AddBook(model, env.WebRootPath);
            //Возврат в начальную страницу
            return RedirectToAction("Index", "Home");

        }

        //Контоллер для удаление книг по id
        //ДОСТУПНА ТОЛЬКО ДЛЯ РОЛИ "librarian"
        [Authorize(Roles = RolesConfig.LIBRARIAN)]
        [HttpGet]
        public async Task<IActionResult> DeleteBook(int? id)
        {
            await bookControl.DeleteBook(id);
            return RedirectToAction("ListBook");
        }

        //Контроллер для возрата книг(фильтрация по имени, языку, автору и жанру; пагинация)
        [AllowAnonymous]
        [Authorize]
        public IActionResult ListBook(BookFilterModel model)
        {
            var modelBooks = bookControl.ListBook(model);
            if (User.Identity.IsAuthenticated)
            {
                modelBooks.Trackings = trackings.GetTrackingsByUserId(userManager.GetUserId(User)).ToList();
                ViewBag.userId = userManager.GetUserId(User);
            }

            return View(modelBooks);
        }

        //Get-контроллер. Для получения одной книги по id
        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> GetThisBook(int? id)
        {
            return View(await bookControl.GetThisBook(id));

        }

        //Post-контроллер.Добавление комментария
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> AddComment(CommentViewModel comment, string UserName)
        {
            await bookControl.AddComment(comment, UserName);
            return RedirectToAction("GetThisBook", new { id = comment.BookId });
        }

        //Post-контроллер.Добавление оценки
        public async Task<IActionResult> AddEvaluation(EvaluationViewModel evaluation)
        {
            await bookControl.AddEvaluation(evaluation);
            return RedirectToAction("GetThisBook", new { id = evaluation.BookId });
        }

        [Authorize(Roles = RolesConfig.LIBRARIAN)]
        [HttpGet]
        public IActionResult Edit(int? id)
        {
            return View(bookControl.Edit(id));
        }

        //Post-контроллер. Редактирование информации о книг
        [HttpPost]
        [Authorize(Roles = RolesConfig.LIBRARIAN)]
        public IActionResult Edit(EditBookViewModel edit)
        {
            bookControl.Edit(edit);
            return RedirectToAction("GetThisBook", new { id = edit.Id });
        }

    }
}

Library/Controllers/RolesController.cs
using Library.Models;
using Library.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;

namespace Library.Controllers
{
    //Администрирование
    [Authorize(Roles = RolesConfig.ADMIN)]
    public class RolesController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;

        private readonly UserManager<User> _userManager;

        public RolesController(RoleManager<IdentityRole> roleManager,
                               UserManager<User> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }

        public IActionResult Index() => View(_roleManager.Roles.ToList());

        public IActionResult Create() => View();

        //Создание нового пользователя
        [HttpPost]
        public async Task<IActionResult> Create(string name)
        {
            if (!string.IsNullOrEmpty(name))
            {
                var result = await _roleManager.CreateAsync(new IdentityRole(name));
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(name);
        }

        //Удаление пользователя
        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);
            if (role != null)
            {
                await _roleManager.DeleteAsync(role);
            }
            return RedirectToAction("Index");

        }

        //Список пользователей
        public IActionResult UserList() => View(_userManager.Users.ToList());
        public async Task<IActionResult> Edit(string userId)
        {
            // получаем пользователя
            var user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // получем список ролей пользователя
                var userRoles = await _userManager.GetRolesAsync(user);
                var allRoles = _roleManager.Roles.ToList();
                var model = new ChangeRoleViewModel
                {
                    UserId = user.Id,
                    UserEmail = user.Email,
                    UserRoles = userRoles,
                    AllRoles = allRoles
                };
                return View(model);
            }

            return NotFound();
        }

        //Редактирование ролей пользователя
        [HttpPost]
        public async Task<IActionResult> Edit(string userId, List<string> roles)
        {
            // получаем пользователя
            var user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // получем список ролей пользователя
                var userRoles = await _userManager.GetRolesAsync(user);
                
                // получаем список ролей, которые были добавлены
                var addedRoles = roles.Except(userRoles);
                // получаем роли, которые были удалены
                var removedRoles = userRoles.Except(roles);

                await _userManager.AddToRolesAsync(user, addedRoles);

                await _userManager.RemoveFromRolesAsync(user, removedRoles);

                return RedirectToAction("UserList");
            }

            return NotFound();
        }
    }
}

Library/Controllers/UserPageController.cs
using Library.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;

namespace Library.Controllers
{
    [Authorize]
    public class UserPageController : Controller
    {
        private readonly UserManager<User> _userManager;

        private readonly ApplicationContext db;

        public UserPageController(ApplicationContext applicationContext, UserManager<User> user)
        {
            db = applicationContext;
            _userManager = user;
        }

        public IActionResult MyPage()
        {
            var user = db.Users.Include(u => u.ReservUser).FirstOrDefault(p => p.Id == _userManager.GetUserId(User));
            return View(user);
        }
    }
}

Library/Controllers/UsersController.cs
using Library.Models;
using Library.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
namespace Library.Controllers
{
    //Администрирование над пользователями
    [Authorize(Roles = RolesConfig.ADMIN)]
    public class UsersController : Controller
    {

        private readonly UserManager<User> _userManager;

        public UsersController(UserManager<User> userManager)
        {
            _userManager = userManager;
        }

        public IActionResult Index() => View(_userManager.Users.ToList());

        public IActionResult Create() => View();

        [HttpPost]
        public async Task<IActionResult> Create(CreateUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = new User { Email = model.Email, UserName = model.Email, NameUser = model.Name };
                var result = await _userManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(model);
        }

        public async Task<IActionResult> Edit(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            var model = new EditUserViewModel { Id = user.Id, Email = user.Email, Name = user.NameUser };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByIdAsync(model.Id);
                if (user != null)
                {
                    user.Email = model.Email;
                    user.UserName = model.Email;


                    var result = await _userManager.UpdateAsync(user);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError(string.Empty, error.Description);
                        }
                    }
                }
            }
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Delete(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user != null)
            {
                await _userManager.DeleteAsync(user);
            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> ChangePassword(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            var model = new ChangePasswordViewModel { Id = user.Id, Email = user.Email };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> ChangePassword(ChangePasswordViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByIdAsync(model.Id);
                if (user != null)
                {
                    var result =
                        await _userManager.ChangePasswordAsync(user, model.OldPassword, model.NewPassword);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError(string.Empty, error.Description);
                        }
                    }
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Пользователь не найден");
                }
            }
            return View(model);
        }
    }
}

Library/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Библиотека</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    <style>
        .main,.navbar-brand{
            font-size:1.5em;
        }
        .body-content{
            background-color:antiquewhite;
           padding-left:10px;
        }
        .foot {
            font-size: 2em;
            color: white;
            text-align: center
        }
       
    </style>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top main">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Библиотека</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Book" asp-action="ListBook">Книги</a></li>
                    @if (User.IsInRole(RolesConfig.ADMIN))
                    {
                    <li><a asp-area="" asp-controller="Users" asp-action="Index">Пользователи</a></li>
                    <li><a asp-controller="Roles" asp-action="Index">Роли</a></li>
                    }
                    @if (User.IsInRole(RolesConfig.LIBRARIAN))
                    {
                        <li><a asp-area="" asp-controller="Book" asp-action="AddBook">Добавить книгу</a></li>
                    <li><a asp-controller="Reservation" asp-action="ListReserv">Список бронь</a></li>
                    }
                    @if (!User.Identity.IsAuthenticated)
                    {
                        <li>
                            <a asp-action="Register" asp-controller="Account">Регистрация</a>
                        </li>
                        <li>  <a asp-action="Login" asp-controller="Account">Войти</a> </li>
                    }
                    else
                    {
                        <li>
                            <a asp-action="MyPage" asp-controller="UserPage">@User.Identity.Name</a>
                        </li>
                        <li> <a asp-action="LogOff" asp-controller="Account">Выход</a> </li>
                    }
                </ul> 
            </div>
        </div>
       
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">

        @RenderBody()
        <hr />
        <footer class="foot">
            <p>&copy; 2019 - Библиотека</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>